sudo: required
before_install:
  - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-full
script:
  - pdflatex -interaction=nonstopmode -halt-on-error LMiranda.tex
  - bibtex -interaction=nonstopmode -halt-on-error LMiranda.tex
  - pdflatex -interaction=nonstopmode -halt-on-error LMiranda.tex
  - pdflatex -interaction=nonstopmode -halt-on-error LMiranda.tex