sudo: required
before_install:
  - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-full
  - tlmgr update --all
script:
  - pdflatex -interaction=nonstopmode -halt-on-error LMiranda.tex
  - bibtex LMiranda.tex
  - pdflatex -interaction=nonstopmode -halt-on-error LMiranda.tex
  - pdflatex -interaction=nonstopmode -halt-on-error LMiranda.tex